go:
    version: 1.15
repository:
    path: github.com/cpanato/github_actions_exporter
build:
    flags: -mod=vendor -a -tags netgo
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        - darwin/amd64
        - windows/amd64
        - linux/arm64
